CREATE TABLE `field_of_studies` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `field_of_studies_name` varchar(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;

INSERT INTO `field_of_studies` VALUES (null, 'Advertising / Media');
INSERT INTO `field_of_studies` VALUES (null, 'Agriculture');
INSERT INTO `field_of_studies` VALUES (null, 'Airline Transport');
INSERT INTO `field_of_studies` VALUES (null, 'Architecture / Urban Studies');
INSERT INTO `field_of_studies` VALUES (null, 'Art & Design');
INSERT INTO `field_of_studies` VALUES (null, 'Biology');
INSERT INTO `field_of_studies` VALUES (null, 'BioTechnology');
INSERT INTO `field_of_studies` VALUES (null, 'Business Studies/Administration/Management');
INSERT INTO `field_of_studies` VALUES (null, 'Chemistry');
INSERT INTO `field_of_studies` VALUES (null, 'Commerce');
INSERT INTO `field_of_studies` VALUES (null, 'Computer Science/Information technology');
INSERT INTO `field_of_studies` VALUES (null, 'Dentistry');
INSERT INTO `field_of_studies` VALUES (null, 'Economics');
INSERT INTO `field_of_studies` VALUES (null, 'Editing and Publication');
INSERT INTO `field_of_studies` VALUES (null, 'Education/Teaching/Training');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Aviation/Aeronautics/Astronautics)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Chemical)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Civil)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Computer/Telecommunication)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Electrical/Electronic)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Environmental/Health/Safety)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Industrial)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Marine)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Material Science)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Mechanical)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Metal Fabrication/Tool & Die/Welding)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Metallurgical)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Others)');
INSERT INTO `field_of_studies` VALUES (null, 'Engineering(Petroleum/Oil/Gas)');
INSERT INTO `field_of_studies` VALUES (null, 'Finance/Accountancy/Banking');
INSERT INTO `field_of_studies` VALUES (null, 'Food and Beverage Preparation/Service Management');
INSERT INTO `field_of_studies` VALUES (null, 'Geographical Science');
INSERT INTO `field_of_studies` VALUES (null, 'Hospitality/Tourism Management');
INSERT INTO `field_of_studies` VALUES (null, 'Human Resource Management');
INSERT INTO `field_of_studies` VALUES (null, 'Humanities/Liberal Arts');
INSERT INTO `field_of_studies` VALUES (null, 'Land Transport');
INSERT INTO `field_of_studies` VALUES (null, 'Law');
INSERT INTO `field_of_studies` VALUES (null, 'Library Management');
INSERT INTO `field_of_studies` VALUES (null, 'Linguistics/Translation & Interpretation');
INSERT INTO `field_of_studies` VALUES (null, 'Mass Communications');
INSERT INTO `field_of_studies` VALUES (null, 'Mathematics');
INSERT INTO `field_of_studies` VALUES (null, 'Medical Science');
INSERT INTO `field_of_studies` VALUES (null, 'Medicine');
INSERT INTO `field_of_studies` VALUES (null, 'Merchant Marine');
INSERT INTO `field_of_studies` VALUES (null, 'Music/Performing Arts Studies');
INSERT INTO `field_of_studies` VALUES (null, 'Nursing');
INSERT INTO `field_of_studies` VALUES (null, 'Others');
INSERT INTO `field_of_studies` VALUES (null, 'Personal Services & Building/Ground Services');
INSERT INTO `field_of_studies` VALUES (null, 'Pharmacy/Pharmacology');
INSERT INTO `field_of_studies` VALUES (null, 'Physics');
INSERT INTO `field_of_studies` VALUES (null, 'Protective Services & Management');
INSERT INTO `field_of_studies` VALUES (null, 'Quantity Survey');
INSERT INTO `field_of_studies` VALUES (null, 'Sales & Marketing');
INSERT INTO `field_of_studies` VALUES (null, 'Science & Technology');
INSERT INTO `field_of_studies` VALUES (null, 'Secretarial');
INSERT INTO `field_of_studies` VALUES (null, 'Textile/Fashion Design & Production');
INSERT INTO `field_of_studies` VALUES (null, 'Veterinary');
INSERT INTO `field_of_studies` VALUES (null, 'Shipping / Shipbuilding');
INSERT INTO `field_of_studies` VALUES (null, 'Sports & Recreation');
INSERT INTO `field_of_studies` VALUES (null, 'Steel Fabrication');
INSERT INTO `field_of_studies` VALUES (null, 'Stockbroking / Securities');
INSERT INTO `field_of_studies` VALUES (null, 'Telecommunication');
INSERT INTO `field_of_studies` VALUES (null, 'Textiles / Garment');
INSERT INTO `field_of_studies` VALUES (null, 'Tobacco');
INSERT INTO `field_of_studies` VALUES (null, 'Transportation Services');
INSERT INTO `field_of_studies` VALUES (null, 'Travel / Tourism');
INSERT INTO `field_of_studies` VALUES (null, 'Utilities');
INSERT INTO `field_of_studies` VALUES (null, 'Wood & Fibre');
